---
- name: Run Terraform modules in sequence
  hosts: localhost
  tasks:

    - name: Initialize RDS-AuroraPostgreSQL module
      command: >
        terraform init
        -backend-config="bucket=vmanep-use1-terraform-creation"
        -backend-config="key=state-rds-pg.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=vmanep-use1-dev3-csf"
        -backend-config="dynamodb_table=vmanep-use1-terraform-creation"
      args:
        chdir: ../../rdsAuroraPostgreSql
    - name: Apply RDS-AuroraPostgreSQL module
      cloud.terraform.terraform:
        project_path: ../../rdsAuroraPostgreSql
        workspace: vmanep-use1-dev3-csf
        state: present         
        variables_files: ../environment/tfvars/RDS-AuroraPostgreSQL.tfvars
      register: rdsAuroraPostgreSql_outputs
    - debug: var=rdsAuroraPostgreSql_outputs.stdout_lines
    - name: Initialize MSK module
      command: >
        terraform init
        -backend-config="bucket=vmanep-use1-terraform-creation"
        -backend-config="key=state-msk.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=vmanep-use1-dev3-csf"
        -backend-config="dynamodb_table=vmanep-use1-terraform-creation"
      args:
        chdir: ../../msk
    - name: Apply MSK module
      cloud.terraform.terraform:
        project_path: ../../msk
        workspace: vmanep-use1-dev3-csf
        state: present        
        variables_files: ../environment/tfvars/MSK.tfvars
      register: msk_outputs
    - debug: var=msk_outputs.stdout_lines
