---
- name: Run Terraform modules in sequence
  hosts: localhost
  tasks:

    - name: Initialize RDS-AuroraPostgreSQL module
      command: >
        terraform init
        -backend-config="bucket=vmanep-use1-terraform-creation"
        -backend-config="key=state-rds-pg.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=vmanep-use1-qa5-csf"
        -backend-config="dynamodb_table=vmanep-use1-terraform-creation"
      args:
        chdir: ../../rdsAuroraPostgreSql
    - name: Plan RDS-AuroraPostgreSQL module
      cloud.terraform.terraform:
        project_path: ../../rdsAuroraPostgreSql
        workspace: vmanep-use1-qa5-csf
        state: planned
        plan_file: terraform.tfplan
        variables_files: ../environment/tfvars/RDS-AuroraPostgreSQL.tfvars
      register: rdsAuroraPostgreSql_outputs
    - debug: var=rdsAuroraPostgreSql_outputs.stdout_lines
    - name: Initialize MSK module
      command: >
        terraform init
        -backend-config="bucket=vmanep-use1-terraform-creation"
        -backend-config="key=state-msk.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=vmanep-use1-qa5-csf"
        -backend-config="dynamodb_table=vmanep-use1-terraform-creation"
      args:
        chdir: ../../msk
    - name: Plan MSK module
      cloud.terraform.terraform:
        project_path: ../../msk
        workspace: vmanep-use1-qa5-csf
        state: planned
        plan_file: terraform.tfplan
        variables_files: ../environment/tfvars/MSK.tfvars
      register: msk_outputs
    - debug: var=msk_outputs.stdout_lines
    - name: Initialize Elasticsearch module
      command: >
        terraform init
        -backend-config="bucket=vmanep-use1-terraform-creation"
        -backend-config="key=state-es.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=vmanep-use1-qa5-csf"
        -backend-config="dynamodb_table=vmanep-use1-terraform-creation"
      args:
        chdir: ../../es_os
    - name: Plan Elasticsearch module
      cloud.terraform.terraform:
        project_path: ../../es_os
        workspace: vmanep-use1-qa5-csf
        state: planned
        plan_file: terraform.tfplan
        variables_files: ../environment/tfvars/Elasticsearch.tfvars
      register: es_os_outputs
    - debug: var=es_os_outputs.stdout_lines
    - name: Initialize EKS module
      command: >
        terraform init
        -backend-config="bucket=vmanep-use1-terraform-creation"
        -backend-config="key=state-eks.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=vmanep-use1-qa5-csf"
        -backend-config="dynamodb_table=vmanep-use1-terraform-creation"
      args:
        chdir: ../../eks
    - name: Plan EKS module
      cloud.terraform.terraform:
        project_path: ../../eks
        workspace: vmanep-use1-qa5-csf
        state: planned
        plan_file: terraform.tfplan
        variables_files: ../environment/tfvars/EKS.tfvars
      register: eks_outputs
    - debug: var=eks_outputs.stdout_lines
    - name: Initialize Route53 module
      command: >
        terraform init
        -backend-config="bucket=vmanep-use1-terraform-creation"
        -backend-config="key=state-route53.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=vmanep-use1-qa5-csf"
        -backend-config="dynamodb_table=vmanep-use1-terraform-creation"
      args:
        chdir: ../../route53
    - name: Plan Route53 module
      cloud.terraform.terraform:
        project_path: ../../route53
        workspace: vmanep-use1-qa5-csf
        state: planned
        plan_file: terraform.tfplan
        variables_files: ../environment/tfvars/Route53.tfvars
      register: route53_outputs
    - debug: var=route53_outputs.stdout_lines
    - name: Initialize EFS module
      command: >
        terraform init
        -backend-config="bucket=vmanep-use1-terraform-creation"
        -backend-config="key=state-efs.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=vmanep-use1-qa5-csf"
        -backend-config="dynamodb_table=vmanep-use1-terraform-creation"
      args:
        chdir: ../../efs
    - name: Plan EFS module
      cloud.terraform.terraform:
        project_path: ../../efs
        workspace: vmanep-use1-qa5-csf
        state: planned
        plan_file: terraform.tfplan
        variables_files: ../environment/tfvars/EFS.tfvars
      register: efs_outputs
    - debug: var=efs_outputs.stdout_lines
    - name: Initialize ArgoCD module
      command: >
        terraform init
        -backend-config="bucket=vmanep-use1-terraform-creation"
        -backend-config="key=state-argocd.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=vmanep-use1-qa5-csf"
        -backend-config="dynamodb_table=vmanep-use1-terraform-creation"
      args:
        chdir: ../../argocd
    - name: Plan ArgoCD module
      cloud.terraform.terraform:
        project_path: ../../argocd
        workspace: vmanep-use1-qa5-csf
        state: planned
        plan_file: terraform.tfplan
        variables_files: ../environment/tfvars/ArgoCD.tfvars
      register: argocd_outputs
    - debug: var=argocd_outputs.stdout_lines

    - name: Test password presence
      vars:
        username: "admin" 
        password: "ThisIsAVeryStrooongPasswordIsn'tIT?"