---
- name: Run Terraform modules in sequence
  hosts: localhost
  tasks:

    - name: Initialize MSK module
      command: >
        terraform init
        -backend-config="bucket=my-terraform-state-bucket"
        -backend-config="key=state-msk.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=dev1"
        -backend-config="dynamodb_table=my-terraform-state-lock-table"
      args:
        chdir: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/msk
    - name: Apply MSK module
      cloud.terraform.terraform:
        project_path: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/msk
        workspace: 
        state: present        
        variables_files: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/config/MSK.tfvars
      register: msk_outputs
    - debug: var=msk_outputs.stdout_lines
    - name: Initialize Elasticsearch module
      command: >
        terraform init
        -backend-config="bucket=my-terraform-state-bucket"
        -backend-config="key=state-es.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=dev1"
        -backend-config="dynamodb_table=my-terraform-state-lock-table"
      args:
        chdir: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/es_os
    - name: Apply Elasticsearch module
      cloud.terraform.terraform:
        project_path: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/es_os
        workspace: 
        state: present
        variables_files: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/config/Elasticsearch.tfvars
      register: es_os_outputs
    - debug: var=es_os_outputs.stdout_lines
    - name: Remove existing kafka_conn_info block
      replace:
        path: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/config/EKS.tfvars
        regexp: 'kafka_conn_info\s*=\s*\{(?:[^{}]*|\{[^{}]*\})*\}'
        replace: ''

    - name: Remove existing es_info block
      replace:
        path: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/config/EKS.tfvars
        regexp: 'es_info = \{[^}]*\}'
        replace: ''

    - name: Create eks.tfvars with module outputs
      blockinfile:
        path: /var/lib/jenkins/workspace/Test
    - name: Initialize EKS module
      command: >
        terraform init
        -backend-config="bucket=my-terraform-state-bucket"
        -backend-config="key=state-eks.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=dev1"
        -backend-config="dynamodb_table=my-terraform-state-lock-table"
      args:
        chdir: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/eks
    - name: Apply EKS module
      cloud.terraform.terraform:
        project_path: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/eks
        workspace: 
        state: present
        variables_files: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/config/EKS.tfvars
      register: eks_outputs
    - debug: var=eks_outputs.stdout_lines
