---
- name: Run Terraform modules in sequence
  hosts: localhost
  tasks:

    - name: Initialize MSK module
      command: >
        terraform init
        -backend-config="bucket=vmanep-use1-terraform-creation"
        -backend-config="key=state-msk.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=testfabrizio"
        -backend-config="dynamodb_table=vmanep-use1-terraform-creation"
      args:
        chdir: ../terraform/msk
    - name: Apply MSK module
      cloud.terraform.terraform:
        project_path: ../terraform/msk
        workspace: testfabrizio
        state: absent
        variables_files: ../../environment/tfvarsMSK.tfvars
      register: msk_outputs
    - debug: var=msk_outputs.stdout_lines
