---
- name: Run Terraform modules in sequence
  hosts: localhost
  tasks:

    - name: Initialize MSK module
      command: >
        terraform init
        -backend-config="bucket=my-terraform-state-bucket"
        -backend-config="key=state-msk.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=dev1"
        -backend-config="dynamodb_table=my-terraform-state-lock-table"
      args:
        chdir: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/csf_devops_cn_baserepo/msk
    - name: Apply MSK module
      cloud.terraform.terraform:
        project_path: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/csf_devops_cn_baserepo/msk
        workspace: 
        state: absent
        variables_files: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/csf_devops_cn_baserepo/config/MSK.tfvars
      register: msk_outputs
    - debug: var=msk_outputs.stdout_lines
