---
- name: Run Terraform modules in sequence
  hosts: localhost
  tasks:

    - name: Initialize MSK module
      command: >
        terraform init
        -backend-config="bucket=my-terraform-state-bucket"
        -backend-config="key=state-msk.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=dev1"
        -backend-config="dynamodb_table=my-terraform-state-lock-table"
      args:
        chdir: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/csf_devops_cn_baserepo/msk
    - name: Plan MSK module
      cloud.terraform.terraform:
        project_path: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/csf_devops_cn_baserepo/msk
        workspace: 
        state: planned
        plan_file: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/csf_devops_cn_baserepo/msk/terraform.tfplan
        variables_files: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/csf_devops_cn_baserepo/config/MSK.tfvars
      register: msk_outputs
    - debug: var=msk_outputs.stdout_lines
    - name: Initialize Elasticsearch module
      command: >
        terraform init
        -backend-config="bucket=my-terraform-state-bucket"
        -backend-config="key=state-es.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=dev1"
        -backend-config="dynamodb_table=my-terraform-state-lock-table"
      args:
        chdir: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/csf_devops_cn_baserepo/es_os
    - name: Plan Elasticsearch module
      cloud.terraform.terraform:
        project_path: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/csf_devops_cn_baserepo/es_os
        workspace: 
        state: planned
        plan_file: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/csf_devops_cn_baserepo/es_os/terraform.tfplan
        variables_files: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/csf_devops_cn_baserepo/config/Elasticsearch.tfvars
      register: es_os_outputs
    - debug: var=es_os_outputs.stdout_lines
    - name: Initialize EKS module
      command: >
        terraform init
        -backend-config="bucket=my-terraform-state-bucket"
        -backend-config="key=state-eks.tfstate"
        -backend-config="region=us-east-1"
        -backend-config="workspace_key_prefix=dev1"
        -backend-config="dynamodb_table=my-terraform-state-lock-table"
      args:
        chdir: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/csf_devops_cn_baserepo/eks
    - name: Plan EKS module
      cloud.terraform.terraform:
        project_path: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/csf_devops_cn_baserepo/eks
        workspace: 
        state: planned
        plan_file: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/csf_devops_cn_baserepo/eks/terraform.tfplan
        variables_files: /var/lib/jenkins/workspace/Test Create Ansible files for Environment/csf_devops_cn_baserepo/config/EKS.tfvars
      register: eks_outputs
    - debug: var=eks_outputs.stdout_lines
