name: git-secrets scan

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write
  pull-requests: write


jobs:
  scan-secrets:
    name: Scan with git-secrets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main]    
    defaults:
      run:
        shell: bash  

    steps:
      - name: Checkout this code
        uses: actions/checkout@v4

      - name: Install git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          sudo make install

      - name: configure git-secrets
        run: |
          git secrets --install
          git secrets --register-aws
          # Add additional custom patterns if needed
          # git secrets --add 'your-regex-here'
          git secrets --add 'password\s*=\s*.+'
          git secrets --add --allowed --literal 'ex@mplepassword'
          git secrets --add 'master_password\s*=\s*.+'
          git secrets --add 'password\s*:\s*.+'
          git secrets --add 'password:\s*\s*.+'

      - name: Scan for secrets
        run: |
          git secrets --scan -r 

