name: 'github'

on:
  push:
    branches:
      - io-test
    paths:
      - .github/workflows/github.yml
      - terraform/github/**
  pull_request:
    paths:
      - .github/workflows/github.yml
      - terraform/github/**
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: terraform/github

permissions:
    pull-requests: write
    contents: write
    security-events: write

jobs:
    terraform:
        uses: VoxSmartLtd/voxsmart-devops/.github/workflows/terraform.yml@io-test
        with:
            terraform_working_directory: terraform/github
            environment: dev
            github_runner: ubuntu-22.04
            terraform_version: 1.6.2
        secrets: inherit
