name: Gitleaks Secret Scan

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  id-token: write
  pull-requests: write


jobs:
  gitleaks-scan:
    name: Run Gitleaks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main]    
    defaults:
      run:
        shell: bash  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --report-format sarif --report-path=gitleaks.sarif

      - name: Upload Gitleaks Report
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

