name: Terraform Checks
on:
  push:
    paths:
      - '**/*.tfvars'
      - '**/*.tf'
  
    branches:
      - io-test

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install unzip (for act)
        run: |
          apt-get update && apt-get install -y unzip  

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate  