name: Secrets Scanning with GitHub Actions and TruffleHog

# Controls when the workflow will run
on:
# Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "io-test" ]
  pull_request:
    branches: [ "io-test" ]

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  Trivy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    

    steps:
      - name: Some Checks
        run: |
          pwd
          ls -al 
          echo "|--- GITHUB.EVENT.PULL_REQUEST.HEAD.REF ${{ github.event.pull_request.head.ref }}"
          echo "|--- GITHUB REF ${{ github.ref }}"
          
     

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          #token: ${{ secrets.GH_CI_TOKEN }}

      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.15.0 # Pinned, pending fix to https://github.com/aquasecurity/trivy/issues/5752
        id: security
        with:
          scan-type: 'config'
          scan-ref: ${{ inputs.terraform_working_directory }}
          hide-progress: false
          #format: 'sarif'
          #output: 'trivy-results.sarif'
          format: "table"
          output: trivy-result.txt
          exit-code: 0
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Check Trivy result file
        run: cat trivy-result.txt    


      - name: Format Trivy Scan Result
        run: |
          if [ -s trivy-result.txt ]; then
            echo -e "## Vulnerability Scan Results\n<details><summary>Details</summary>\n\n\`\`\`\n$(cat trivy-result.txt)\n\`\`\`\n</details>" > formatted-trivy-result.md
          else
            echo -e "## Vulnerability Scan Results\nNo vulnerabilities were detected." > formatted-trivy-result.md
          fi  
