name: Secrets Scanning
on:
  push:
    paths:
      - '**/*.tfvars'
      - '**/*.yml'
      - '**/*.yaml'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write
#  issues: write
#  pull-requests: write

jobs:
  trivy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main]  
    defaults:
      run:
        shell: bash
      
    steps:
      - name: Show OS Version
        run: |
          echo "🖥️ Operating System Information:"
          uname -a  # Kernel and architecture info
          cat /etc/os-release  # OS version details  


      - name: Some Checks
        run: |
          pwd
          ls -al 
          echo "|--- GITHUB.EVENT.PULL_REQUEST.HEAD.REF ${{ github.event.pull_request.head.ref }}"
          echo "|--- GITHUB REF ${{ github.ref }}"
       

      - name: Checkout
        uses: actions/checkout@v4
        with:
          #ref: ${{ github.event.pull_request.head.ref || github.ref }} # The branch, tag or SHA to checkout
          ref: main
          #token: ${{ secrets.GH_CI_TOKEN }}

      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.15.0 # Pinned, pending fix to https://github.com/aquasecurity/trivy/issues/5752
        id: security
        with:
          scan-type: 'config'
          #scan-ref: ${{ inputs.terraform_working_directory }}
          scan-ref: '.'  
          hide-progress: false
          #format: 'sarif'
          #output: 'trivy-results.sarif'
          format: "table"
          output: trivy-result.txt
          exit-code: 0
          ignore-unfixed: true
          #vuln-type: 'os,library'  
          severity: 'CRITICAL,HIGH'

      - name: Check Trivy result file
        run: cat trivy-result.txt    


      - name: Format Trivy Scan Result
        run: |
          if [ -s trivy-result.txt ]; then
            echo -e "## Vulnerability Scan Results\n<details><summary>Details</summary>\n\n\`\`\`\n$(cat trivy-result.txt)\n\`\`\`\n</details>" > formatted-trivy-result.md
          else
            echo -e "## Vulnerability Scan Results\nNo vulnerabilities were detected." > formatted-trivy-result.md
          fi
          
      - name: Comment PR with Trivy scan results
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: formatted-trivy-result.md
          
      - name: Clean up Trivy result file
        run: rm -f trivy-result.txt formatted-trivy-result.md    
