name: Secrets Scanning with GitHub Actions and TruffleHog

# Controls when the workflow will run
on:
# Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "io-test" ]
  pull_request:
    branches: [ "io-test" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build"
  #build:
  secretsscan: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
        run:
          shell: bash
          working-directory: ./tfvars

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Install dependencies
      run: |
        apt-get update && apt-get install sudo -y
        sudo apt-get update
        #apt-cache policy docker-ce
        sudo apt-get install curl build-essential git lsb-release unzip -y
        #sudo apt-get install git docker-ce -y
        #sudo apt-get install -y ca-certificates curl gnupg
        sudo install -m 0755 -d /etc/apt/keyrings
        #curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc > /dev/null
        #sudo chmod a+r /etc/apt/keyrings/docker.asc
        #echo "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        #sudo apt-get update

        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo tee /etc/apt/keyrings/docker.asc > /dev/null
        sudo chmod a+r /etc/apt/keyrings/docker.asc

        # Add Docker repository for Debian
        echo "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update

        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Runs a single command using the runners shell
    - name: confirm bearings
      run: |
       pwd
       ls -al
       echo "|--- BRANCH IS --  ${{ github.event.repository.default_branch }} ---|"
       echo "|--- WORKSPACE ${{ github.workspace }} ---|"
       #trufflehog --no-update filesystem --directory=${{ github.workspace }} --json > /tmp/trufflehog.json

    - name: Scan with TruffleHog
      id: trufflehog
      uses: trufflesecurity/trufflehog@main
      continue-on-error: true
      with:
         path: ./tfvars
         base: io-test
         #base: "${{ github.event.repository.default_branch }}"
         #head: HEAD
         extra_args: --debug
       

    # Upload the scan output
    #- name: Upload the scan output
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: scan_results
    #    path: /tmp/trufflehog.json
    #    retention-days: 2