name: TruffleHog Password Regex Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  scan:
    name: Run TruffleHog in Docker with Custom Detector
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run TruffleHog Docker with Custom Detector
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            -w /repo \
            ghcr.io/trufflesecurity/trufflehog:latest \
            filesystem \
              --directory /repo \
              --detectors /repo/custom-password-detector.yaml

